version: "2.2"
services:
  postgres:
    image: postgres:12.0
    container_name: todo-local-pg
    ports:
      - "15432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: test
      POSTGRES_DB: todo
  migration:
    image: migrate/migrate:v4.7.0
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./migrations/:/migrations/
    command: -path=/migrations/ -database postgres://postgres:test@todo-local-pg:5432/todo?sslmode=disable up
  todo:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: todo_local
    depends_on:
      postgres:
        condition: service_healthy
      migration:
        condition: service_started
    ports:
      - "19000:9000"
    volumes:
      - ./config/:/config/
    command: -cfg /config/docker.yaml
